# Turtle Program
#
#
""" Created by: AK1R4S4T0H
"""
import turtle
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
import os

root = tk.Tk()
root.title("STAR")
canvas = turtle.Screen()
canvas.bgcolor("black")

def start_drawing():
    turtle_screen = turtle.Screen()
    turtle_screen.bgcolor("black")

    while True:
        turtle.Turtle()
        turtle.speed(0)
        turtle.penup()
        turtle.goto(0,0)
        turtle.pendown()
        turtle.color("#FF0000")
        turtle.forward(15)
        turtle.right(20)
        turtle.color("#3c79b8")
        turtle.forward(40)
        turtle.right(20)
        turtle.left(50)
        turtle.color("#00BB02")
        turtle.backward(50)
        turtle.right(9)
        turtle.color("#00FFFF")
        turtle.forward(20)
        turtle.left(9)
        turtle.color("yellow")
        turtle.left(4.5)
        turtle.forward(42)
        turtle.color("#BB00AA")
        turtle.circle(4.5)
        turtle.color("#00FF00")
        turtle.circle(9)
        turtle.color('pink')
        turtle.circle(13.5)
        turtle.circle(18)
        turtle.color('skyblue')
        turtle.circle(24)
        turtle.color("#BB00AA")
        turtle.circle(36)
        turtle.color("yellow")
        turtle.left(4.5)
        turtle.forward(42)
        turtle.color("#00FFFF")
        turtle.forward(20)
        turtle.left(9)
        turtle.color("#00BB02")
        turtle.backward(50)
        turtle.right(9)
        turtle.color("#3c79b8")
        turtle.forward(40)
        turtle.right(20)
        turtle.left(50)
        turtle.color("#FF0000")
        turtle.forward(15)
        turtle.right(20)
        turtle.color('violet')
        turtle.circle(4.5)
        turtle.color('pink')
        turtle.circle(9)
        turtle.color('white')
        turtle.circle(13.5)
        turtle.color('salmon')
        turtle.circle(18)
        turtle.color('teal')
        turtle.circle(24)
        turtle.color('forestgreen')
        turtle.circle(36)
        turtle.color("#FF0000")
        turtle.forward(15)
        turtle.right(20)
        turtle.color("#3c79b8")
        turtle.forward(40)
        turtle.right(20)
        turtle.left(50)
        turtle.color("#00BB02")
        turtle.backward(50)
        turtle.right(9)
        turtle.color("#00FFFF")
        turtle.forward(20)
        turtle.left(9)
        turtle.color("yellow")
        turtle.left(4.5)
        turtle.forward(42)
        turtle.color("#BB00AA")
        turtle.circle(4.5)
        turtle.color("#00FF00")
        turtle.circle(9)
        turtle.color('pink')
        turtle.circle(13.5)
        turtle.circle(18)
        turtle.color('skyblue')
        turtle.circle(24)
        turtle.color("#BB00AA")
        turtle.circle(36)
        turtle.color("yellow")
        turtle.left(4.5)
        turtle.forward(42)
        turtle.color("#00FFFF")
        turtle.forward(20)
        turtle.left(9)
        turtle.color("#00BB02")
        turtle.backward(50)
        turtle.right(9)
        turtle.color("#3c79b8")
        turtle.forward(40)
        turtle.right(20)
        turtle.left(50)
        turtle.color("#FF0000")
        turtle.forward(15)
        turtle.right(20)
        turtle.color('violet')
        turtle.circle(4.5)
        turtle.color('pink')
        turtle.circle(9)
        turtle.color('white')
        turtle.circle(13.5)
        turtle.color('salmon')
        turtle.circle(18)
        turtle.color('teal')
        turtle.circle(24)
        turtle.color('forestgreen')
        turtle.circle(36)
        turtle.color("#FF0000")
        turtle.forward(15)
        turtle.right(20)
        turtle.color("#3c79b8")
        turtle.forward(40)
        turtle.right(20)
        turtle.left(50)
        turtle.color("#00BB02")
        turtle.backward(50)
        turtle.right(9)
        turtle.color("#00FFFF")
        turtle.forward(20)
        turtle.left(9)
        turtle.color("yellow")
        turtle.left(4.5)
        turtle.forward(42)
        

def stop_drawing():
    turtle.penup()
    turtle.hideturtle()
    turtle.done = True

def save_image():
    file_name = filedialog.asksaveasfilename(defaultextension=".png")
    if file_name:
        try:
            canvas.getcanvas().postscript(file="turtle.eps")
            os.system("convert turtle.eps " + file_name)
        except Exception as e:
            messagebox.showerror("Error", str(e))

start_button = tk.Button(root, text="Start Drawing", command=start_drawing)
start_button.pack(side=tk.LEFT, padx=10, pady=10)

stop_button = tk.Button(root, text="Stop Drawing", command=stop_drawing)
stop_button.pack(side=tk.LEFT, padx=10, pady=10)

save_button = tk.Button(root, text="Save Image", command=save_image)
save_button.pack(side=tk.LEFT, padx=10, pady=10)

root.mainloop()
